<a href="https://colab.research.google.com/github/haeun1star/Mobis_Python_2023/blob/main/231208_python_module%2C%20package.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 모듈


In [ ]:
import random

random.random()

0.6580600646048357

In [ ]:
dice = random.randint(1, 6)
print(dice)

4


In [ ]:
random.randrange(0, 11, 2)

8

In [ ]:
menu = ['A', 'B', 'C']
random.choice(menu)

'A'

In [ ]:
random.sample([1, 2, 3, 4, 5], 2)

[1, 3]

## 패키지

In [ ]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5, 6, 7]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
data2 = [0.1, 6, 3, 26, 6.4]
a2 = np.array(data2)
a2

array([ 0.1,  6. ,  3. , 26. ,  6.4])

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('float64')

In [ ]:
np.array([0.5, 5, 0.02, 10])

array([ 0.5 ,  5.  ,  0.02, 10.  ])

In [ ]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10, 2) # start, step, stop

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1, 10) # start, stop

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5) # stop

array([0, 1, 2, 3, 4])

In [ ]:
b1 = np.arange(12).reshape(4, 3)
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b1.shape

(4, 3)

In [ ]:
b2 = np.arange(5)
b2

array([0, 1, 2, 3, 4])

In [ ]:
b2.shape

(5,)

In [ ]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(2, 3)

array([[0.58046025, 0.55217373, 0.74529303],
       [0.85148019, 0.88863963, 0.01282607]])

In [ ]:
np.random.rand(2, 3, 4)

array([[[0.8228548 , 0.48285231, 0.84056168, 0.49388792],
        [0.79960066, 0.29140017, 0.14368667, 0.73026734],
        [0.83927097, 0.41545081, 0.28071963, 0.78832289]],

       [[0.38680835, 0.12452632, 0.14143118, 0.99647988],
        [0.64375097, 0.72942149, 0.20954705, 0.45199979],
        [0.09296889, 0.0241313 , 0.33644965, 0.08977237]]])

In [ ]:
np.random.randint(10, size=(3, 4))

array([[2, 2, 5, 6],
       [1, 5, 8, 7],
       [7, 9, 8, 4]])

배열의 연산

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [ ]:
arr1 + arr2

array([11, 22, 33, 44])

In [ ]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [ ]:
arr1 * 4

array([ 40,  80, 120, 160])

In [ ]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [ ]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [ ]:
arr1 / arr2

array([10., 10., 10., 10.])

In [ ]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [ ]:
arr1 > 20

array([False, False,  True,  True])

통계를 위한 연산

In [ ]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [ ]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [ ]:
[arr3.min(), arr3.max()]

[0, 4]

In [ ]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [ ]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [ ]:
arr4.cumprod()

array([ 1,  2,  6, 24])

행렬연산

In [ ]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [ ]:
np.dot(A, B)

array([[0, 1],
       [6, 7]])

In [ ]:
A @ B

array([[0, 1],
       [6, 7]])

In [ ]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [ ]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [ ]:
A.T

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
np.linalg.det(A)

-2.0

배열의 indexing / slicing

In [ ]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1[0]

0

In [ ]:
a1[4]

40

In [ ]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
a1[[1, 3, 4]]

array([10, 30, 40])

In [ ]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
a2[0, 2]

30

In [ ]:
a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1]

array([40, 50, 60])

In [ ]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [ ]:
b1[:3]

array([ 0, 10, 20])

In [ ]:
b1[2:]

array([20, 30, 40, 50])

In [ ]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [ ]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [ ]:
b2[1][0:2]

array([40, 50])

## Pandas

In [ ]:
import pandas as pd

In [ ]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s1.values

array([10, 20, 30, 40, 50])

In [ ]:
s2 = pd.Series([10, 20, 'a', 'b', 30.0])
s2

0      10
1      20
2       a
3       b
4    30.0
dtype: object

In [ ]:
s3 = pd.Series([np.nan, 10, 50])
s3

0     NaN
1    10.0
2    50.0
dtype: float64

In [ ]:
index = ['2309', '2310', '2311', '2312']
s4 = pd.Series([30, 60, 80, 120], index = index)
s4

2309     30
2310     60
2311     80
2312    120
dtype: int64

In [ ]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
data_list = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
df2 = pd.DataFrame(data_list)
df2

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [ ]:
index_list = ['2303', '2304', '2305']
columns_list = ['A', 'B', 'C']
df3 = pd.DataFrame(data_list, index = index_list, columns = columns_list)
df3

A   B   C
2303  10  20  30
2304  40  50  60
2305  70  80  90

데이터 연산

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([1, 3, 5, 7, 9])

s1 + s2

0     2
1     5
2     8
3    11
4    14
dtype: int64

In [ ]:
s3 = pd.Series([10, 20, 30, 40])

s1 * s3

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

In [ ]:
table_data = {'Spring': [256.5, 264.3, 215.9, 223.2, 312.8],
              'Summer': [770.6, 567.5, 599.8, 387.1, 446.2],
              'Autumn': [363.5, 231.2, 293.1, 247.7, 381.6],
              'Winter': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['Spring', 'Summer', 'Autumn', 'Winter']
index_list = ['2012', '2013', '2014', '2015', '2016']

df5 = pd.DataFrame(table_data, columns = columns_list, index= index_list)
df5

Spring  Summer  Autumn  Winter
2012   256.5   770.6   363.5   139.3
2013   264.3   567.5   231.2    59.9
2014   215.9   599.8   293.1    76.9
2015   223.2   387.1   247.7   109.1
2016   312.8   446.2   381.6   108.1

In [ ]:
df5.mean()

Spring    254.54
Summer    554.24
Autumn    303.42
Winter     98.66
dtype: float64

In [ ]:
df5.std()

Spring     38.628267
Summer    148.888895
Autumn     67.358496
Winter     30.925523
dtype: float64

In [ ]:
df5.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [ ]:
df5.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [ ]:
df5.describe()

Spring      Summer      Autumn      Winter
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

index, column 확인, 변경

In [ ]:
df6 = pd.DataFrame(data=[['kor', 70], ['math', 80]], columns=['class', 'score'])
df6

class  score
0   kor     70
1  math     80

In [ ]:
df6.index = ['a', 'b']
df6

class  score
a   kor     70
b  math     80

In [ ]:
df6.set_index('class', drop=True, append=False, inplace=True)
df6

score
class       
kor       70
math      80

In [ ]:
df6.reset_index(drop=False, inplace=True)
df6

class  score
0   kor     70
1  math     80

In [ ]:
df6.columns = ['Class', 'Score']
df6

Class  Score
0   kor     70
1  math     80

row/column 선택, 추가, 삭제

In [ ]:
data = pd.read_csv('sample_data/california_housing_train.csv')
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [ ]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
data[1:4]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   

   population  households  median_income  median_house_value  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0

In [ ]:
data['longitude'].head(4)

0   -114.31
1   -114.47
2   -114.56
3   -114.57
Name: longitude, dtype: float64

In [ ]:
data[['longitude','latitude']].head(3)

longitude  latitude
0    -114.31     34.19
1    -114.47     34.40
2    -114.56     33.69

In [ ]:
data.iloc[1:4]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   

   population  households  median_income  median_house_value  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0

In [ ]:
data.iloc[[1, 3, 5], 2:4]

housing_median_age  total_rooms
1                19.0       7650.0
3                14.0       1501.0
5                29.0       1387.0

In [ ]:
data.loc[1:4]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
data.loc[[1, 3, 5], 'longitude':'latitude']

longitude  latitude
1    -114.47     34.40
3    -114.57     33.64
5    -114.58     33.63

In [ ]:
data.loc[data['housing_median_age'] >= 20.0]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
4        -114.57     33.57                20.0       1454.0           326.0   
5        -114.58     33.63                29.0       1387.0           236.0   
6        -114.58     33.61                25.0       2907.0           680.0   
7        -114.59     34.83                41.0        812.0           168.0   
8        -114.59     33.61                34.0       4789.0          1175.0   
...          ...       ...                 ...          ...             ...   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
4           624.0       262.0         1.9250             65500.0  
5           671.0       239.0         3.3438             74000.0  
6          1841.0       633.0         2.6768             82400.0  
7           375.0       158.0         1.7083             48500.0  
8          3134.0      1056.0         2.1782             58400.0  
...           ...         ...            ...                 ...  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16999       806.0       270.0         3.0147             94600.0  

[12174 rows x 9 columns]

In [ ]:
data.loc[data['housing_median_age'] >= 20.0, 'total_bedrooms']

4         326.0
5         236.0
6         680.0
7         168.0
8        1175.0
          ...  
16993     453.0
16994     419.0
16995     394.0
16996     528.0
16999     300.0
Name: total_bedrooms, Length: 12174, dtype: float64

In [ ]:
data.loc[data['housing_median_age'] >= 20.0, ['total_bedrooms']]

total_bedrooms
4               326.0
5               236.0
6               680.0
7               168.0
8              1175.0
...               ...
16993           453.0
16994           419.0
16995           394.0
16996           528.0
16999           300.0

[12174 rows x 1 columns]

In [ ]:
# DataFrame에서 columns가 같은 두 데이터를 세로방향으로 합치기
dfa = pd.DataFrame({'Class1': [95, 92, 98, 100], 'Class2': [91, 93, 97, 99]})
dfa

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99

In [ ]:
dfb = pd.DataFrame({'Class1': [87, 89], 'Class2': [85, 90]})
dfb

Class1  Class2
0      87      85
1      89      90

In [ ]:
dfa.append(dfb)

<ipython-input-119-aacce3d43d99>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dfa.append(dfb)


Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90

In [ ]:
pd.concat([dfa, dfb])

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
0      87      85
1      89      90

In [ ]:
pd.concat([dfa, dfb], ignore_index=True)

Class1  Class2
0      95      91
1      92      93
2      98      97
3     100      99
4      87      85
5      89      90

In [ ]:
dfc = pd.DataFrame({'Class1':[96, 83]})
dfc

Class1
0      96
1      83

In [ ]:
pd.concat([dfa, dfc], ignore_index=True)

Class1  Class2
0      95    91.0
1      92    93.0
2      98    97.0
3     100    99.0
4      96     NaN
5      83     NaN

In [ ]:
# DataFrame에서 index가 같은 두 데이터를 가로방향으로 합치기
dfd = pd.DataFrame({'Class3': [93, 91, 95, 98]})
dfd

Class3
0      93
1      91
2      95
3      98

In [ ]:
dfa.join(dfd)

Class1  Class2  Class3
0      95      91      93
1      92      93      91
2      98      97      95
3     100      99      98

In [ ]:
dfe = pd.DataFrame({'Class4': [82, 91]})
dfe

Class4
0      82
1      91

In [ ]:
dfa.join(dfe)

Class1  Class2  Class4
0      95      91    82.0
1      92      93    91.0
2      98      97     NaN
3     100      99     NaN

In [ ]:
df6 = pd.DataFrame(data=[['kor', 70], ['math', 80]], columns=['class', 'score'])
df6

class  score
0   kor     70
1  math     80

In [ ]:
df6.loc[1, 'score'] = 100
df6

class  score
0   kor     70
1  math    100

In [ ]:
df6.loc[0, 'score'] = df6.loc[0, 'score'] - 5
df6

class  score
0   kor     65
1  math    100

In [ ]:
df7 = pd.DataFrame({'국어': [100, 80],
                    '수학': [75, 90],
                    '영어': [90, 95]}, index = ['A', 'B'])
df7.loc['B', '영어'] = 100
df7['국어'] = df7['국어'] - 5
df7

국어  수학   영어
A  95  75   90
B  75  90  100

In [ ]:
df7.drop('A', inplace=True)
df7

국어  수학   영어
B  75  90  100

결측치 탐색

In [ ]:
data.isna()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
16995      False     False               False        False           False   
16996      False     False               False        False           False   
16997      False     False               False        False           False   
16998      False     False               False        False           False   
16999      False     False               False        False           False   

       population  households  median_income  median_house_value  
0           False       False          False               False  
1           False       False          False               False  
2           False       False          False               False  
3           False       False          False               False  
4           False       False          False               False  
...           ...         ...            ...                 ...  
16995       False       False          False               False  
16996       False       False          False               False  
16997       False       False          False               False  
16998       False       False          False               False  
16999       False       False          False               False  

[17000 rows x 9 columns]

In [ ]:
data.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
data.dropna()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
data.dropna(thresh=4) # 결측값이 아닌 값이 4개 초과인 행은 남기기

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
data.drop_duplicates()
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
data.fillna(0)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]